apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformation
  labels:
    app: transformation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transformation
  template:
    metadata:
      labels:
        app: transformation
    spec:
      containers:
      - name: transformation
        image: pii-guardian/transformation:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: pii-logs
          mountPath: /var/log/pii-guardian
      volumes:
      - name: pii-logs
        emptyDir: {}
